import React from "react";
import { renderToStaticMarkup } from "react-dom/server";
import { legalPages } from "./data/legal.mjs";
import { projects } from "./data/projects.mjs";
import { serviceAlternates, servicePages, servicePaths } from "./data/services.mjs";
import { absoluteUrl, caseAlternates, casePaths, site } from "./data/site.mjs";
import en from "./i18n/en.mjs";
import fr from "./i18n/fr.mjs";
import { CasePage, HomePage, LegalPage, NotFoundPage, ServicePage } from "./pages.jsx";

const translations = { en, fr };

const banner = "<!-- Generated by scripts/build.mjs from src/site. Edit the sources, not this file. -->";

function html(element) {
  return `<!doctype html>\n${banner}\n${renderToStaticMarkup(element)}\n`;
}

// Every page with its translations, so each sitemap entry lists its hreflang siblings.
function sitemapEntries() {
  const entries = Object.values(site.localePaths).map((url) => ({ url, alternates: site.localePaths }));
  for (const page of servicePages) {
    const alternates = serviceAlternates(page);
    for (const url of Object.values(alternates)) entries.push({ url, alternates });
  }
  for (const project of projects) {
    const alternates = caseAlternates(project.slug);
    for (const url of Object.values(alternates)) entries.push({ url, alternates });
  }
  for (const page of legalPages) entries.push({ url: `/${page.path}` });
  return entries;
}

function sitemap() {
  const lastmod = new Date().toISOString().slice(0, 10);
  return `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">
${sitemapEntries()
  .map(({ url, alternates }) => {
    const links = alternates
      ? Object.entries(alternates)
          .map(([code, href]) => `\n    <xhtml:link rel="alternate" hreflang="${code}" href="${absoluteUrl(href)}" />`)
          .join("")
      : "";
    return `  <url>\n    <loc>${absoluteUrl(url)}</loc>\n    <lastmod>${lastmod}</lastmod>${links}\n  </url>`;
  })
  .join("\n")}
</urlset>
`;
}

function manifest() {
  return `${JSON.stringify(
    {
      name: "PixelWaves Digital — Studio",
      short_name: "PixelWaves",
      description: en.meta.description,
      start_url: "/",
      display: "standalone",
      background_color: "#07060b",
      theme_color: "#07060b",
      icons: [
        { src: "/public/brand/icon-192.png", sizes: "192x192", type: "image/png", purpose: "any maskable" },
        { src: "/public/brand/icon-512.png", sizes: "512x512", type: "image/png", purpose: "any maskable" },
      ],
    },
    null,
    2,
  )}\n`;
}

export function renderPages({ assets }) {
  return [
    { path: "index.html", content: html(<HomePage t={en} locale="en" assets={assets} />) },
    { path: "fr/index.html", content: html(<HomePage t={fr} locale="fr" assets={assets} />) },
    ...servicePages.flatMap((page) =>
      Object.keys(translations).map((locale) => ({
        path: `${servicePaths[locale](page).slice(1)}index.html`,
        content: html(<ServicePage t={translations[locale]} locale={locale} page={page} assets={assets} />),
      })),
    ),
    ...projects.flatMap((project, index) => {
      const next = projects[(index + 1) % projects.length];
      return Object.keys(translations).map((locale) => ({
        path: `${casePaths[locale](project.slug).slice(1)}index.html`,
        content: html(<CasePage t={translations[locale]} locale={locale} project={project} next={next} assets={assets} />),
      }));
    }),
    ...legalPages.map((page) => ({ path: page.path, content: html(<LegalPage t={fr} page={page} assets={assets} />) })),
    { path: "404.html", content: html(<NotFoundPage t={en} fr={fr} assets={assets} />) },
    { path: "sitemap.xml", content: sitemap() },
    { path: "robots.txt", content: `User-agent: *\nAllow: /\nSitemap: ${absoluteUrl("/sitemap.xml")}\n` },
    { path: "site.webmanifest", content: manifest() },
  ];
}
